name: ualet_ddd
description: A new Flutter project for Aualet 2.0 implmenting Domain Dirven Disign Architecture.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  auto_route: ^0.5.0
  cupertino_icons: ^0.1.3
  dartz: ^0.9.1
  dio: ^3.0.9
  flushbar: ^1.10.4
  flutter_bloc: ^4.0.0
  freezed_annotation: ^0.7.1
  get_it: ^4.0.2
  injectable: ^0.4.0+1
  json_annotation: ^3.0.1
  kt_dart: ^0.7.0+1
  meta: ^1.1.8
  package_info: ^0.4.1
  provider: ^4.1.3
  shared_preferences: ^0.5.7+3
  uuid: ^2.0.4

dev_dependencies:
  auto_route_generator: ^0.5.0
  build_runner:
  freezed: ^0.10.9
  injectable_generator: ^0.4.1
  json_serializable: ^3.3.0
  lint: ^1.2.0


flutter:
  assets:
    - assets/certs/
    - assets/fonts/
    - assets/images/
    - assets/vectors/

  uses-material-design: true
  fonts:
  - family:  OpenSans
    fonts:
      - asset: assets/fonts/OpenSans-Light.ttf
        weight: 300
      - asset: assets/fonts/OpenSans-Regular.ttf
        weight: 400
      - asset:  assets/fonts/OpenSans-SemiBold.ttf
        weight: 600
      - asset:  assets/fonts/OpenSans-Bold.ttf
        weight: 700

flutter_intl:
enabled: true
main_locale: es